name: Release

on:
  repository_dispatch:
    types: [poc-attest]

permissions:
  contents: write
  attestations: write
  id-token: write

jobs:
  attest:
    uses: jtorleon-studios-team/.workflows/.github/workflows/release.yml@main
    with:
      tag: ${{ github.event.client_payload.tag }}
